### ISSUE TITLE
Feature: bootstrap icons

### ISSUE THREAD

**Issue by orjanalmen** [tonix-tuft/tempusdominus-bootstrap#10]
As this is bootstrap based and bootstrap released their own icon set, I believe support for that set would be great. Unfortunately I'm not good enough yet to make a PR for it...

**Comment by tonix-tuft** [comment]
Are you talking about Bootstrap 4? Could you link the page with the icons you mention so I can take a look, please? Thank you!

**Comment by tonix-tuft** [comment]
Sorry for only getting back now. GitHub doesn't show me notifications when new issues are opened.

**Comment by orjanalmen** [comment]
https://icons.getbootstrap.com/

**Comment by tonix-tuft** [comment]
Thanks for the link!

Will check it out as soon as I have time. It could be a good to add support for this icon set as well.

**Comment by tonix-tuft** [comment]
I am closing this issue for now because Eonasdan (the original maintainer of tempusdominus-bootstrap) has come back and maybe this integration will happen in the upstream project. We'll see what happens.

Cheers!
